### ISSUE TITLE
[Task] <User Module MySQL Improve>

### ISSUE THREAD

**Issue by nuo-promise** [suparking/shared-trading-system#16]
### Description

imporve user serve db interface.

### Task List

- [x] UserWallet @nuo-promise 
- [x] MerchantWallet @nuo-promise 
- [x] Merchant @nuo-promise 
- [x] CarPark @nuo-promise 
- [x] CarLicense @nuo-promise
